services:
  - type: web
    name: vira-api
    runtime: node
    plan: free
    repo: https://github.com/Sherzod-1998/vira
    branch: master
    buildCommand: npm ci --include=dev && npm run build:api
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: MONGO_PROD
        sync: false
      - key: SECRET_TOKEN
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
